name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate Xcode project
      run: swift package generate-xcodeproj
    - name: Build
      run: xcodebuild build -sdk iphoneos -scheme "TwiAuth-Package"
    - name: Run tests
      run: xcodebuild test -destination "name=iPhone 11" -scheme "TwiAuth-Package"
